# Generated by Django 4.0.4 on 2022-08-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_product_description_alter_product_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
