# Generated by Django 4.0.4 on 2022-08-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_shippingaddress_address2_billingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
